# Generated by Django 4.1.3 on 2022-12-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_voicing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='voicing_time',
        ),
    ]
