# Generated by Django 4.1.3 on 2022-12-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_voicing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_auto_transition',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_video',
            field=models.BooleanField(default=True),
        ),
    ]
