# Generated by Django 4.1.3 on 2022-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='instruction',
            field=models.TextField(blank=True),
        ),
    ]
