# Generated by Django 4.1.3 on 2022-12-02 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
