# Generated by Django 4.1.3 on 2022-12-09 12:10

import card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_path',
            field=models.FileField(blank=True, upload_to=card.models.card_directory_path_video),
        ),
    ]
